
export enum MessageSender {
    USER = 'user',
    AI = 'ai',
}

export enum AppView {
    CHAT = 'chat',
    SETTINGS = 'settings',
    BRAND = 'brand',
    PEOPLE = 'people',
    CONCEPTS = 'concepts',
    JOURNAL = 'journal',
    AGENDA = 'agenda',
    CALENDAR = 'calendar',
    POMODORO = 'pomodoro',
    GAMIFICATION = 'gamification',
    POLARIS = 'polaris',
    SEARCH = 'search',
    DELTA = 'delta',
}

export interface FileAttachment {
    name: string;
    type: string;
    size: string;
}

export interface Message {
    id: string;
    threadId: string;
    sender: MessageSender;
    text: string;
    file?: FileAttachment;
    createdAt: number;
}

export interface Thread {
    id: string;
    title: string;
    createdAt: number;
    updatedAt: number;
    artifactContent?: string;
}

export interface JITSnippet {
    id: string;
    threadId: string;
    tags: string[];
    text: string;
    relevance: number;
    createdAt: number;
}

export interface JournalEntry {
    id: string;
    title: string;
    content: string;
    createdAt: number;
    autoGenerated?: boolean;
    sourceThreadId?: string;
    tags?: string[];
    grade?: number; // 1-5
    gradeNotes?: string;
    scope?: 'personal' | 'professional';
    sentiment?: 'positive' | 'neutral' | 'negative';
    metadata?: Record<string, string>;
}

export interface AgendaItem {
    id: string;
    title: string;
    description?: string;
    status: 'todo' | 'in-progress' | 'done';
    dueAt?: number;
    createdAt: number;
    deliverableId?: string;
    estimatedTime?: number; // Minutes
    priority?: 'low' | 'medium' | 'high';
    dependencies?: string[]; // IDs of tasks that must be completed first
    tags?: string[];
    completedAt?: number;
    notes?: string;
}

export interface Deliverable {
    id: string;
    title: string;
    description: string;
    scope: 'personal' | 'professional';
    priority: 'low' | 'medium' | 'high';
    tags: string[];
    guardrails: string;
    successCriteria: string;
    createdAt: number;
}

export interface AgendaSession {
    id: string;
    mode: 'manual' | 'semi-auto' | 'auto';
    deliverableIds: string[];
    taskSequence?: string[]; // Ordered list of agenda item IDs for workflow
    startedAt: number;
    endedAt?: number;
    status: 'active' | 'paused' | 'completed';
    summary?: string;
    notes?: string;
    currentTaskIndex?: number; // For tracking progress through sequence
    autonomousAgentConfig?: {
        personality?: string; // How the agent should act
        decisionStyle?: string; // How it makes decisions
        communicationStyle?: string; // How it communicates
    };
    sessionGoals?: string[]; // Goals for this session
    xpAwarded?: number; // XP earned during session
    createdAt?: number;
    updatedAt?: number;
}

export interface PostMortem {
    id: string;
    sessionId: string;
    notes: string;
    grade?: number;
    createdAt: number;
}

export interface CalendarEvent {
    id: string;
    title: string;
    description?: string;
    startAt: number;
    endAt: number;
    location?: string;
    meetingLink?: string;
    eventType?: 'meeting' | 'call' | 'appointment' | 'event' | 'deadline' | 'reminder' | 'other';
    participants?: string[]; // Array of PeopleRecord IDs
    tags?: string[];
    color?: string; // Hex color for calendar display
    isRecurring?: boolean;
    recurrenceRule?: string; // e.g., "daily", "weekly", "monthly"
    reminderMinutes?: number; // Minutes before event to remind
    createdAt: number;
    updatedAt?: number;
}

export interface PomodoroSession {
    id: string;
    label: string;
    startedAt: number;
    durationMinutes: number;
}

export interface BrandRecord {
    id: string;
    name: string;
    description: string;
    createdAt: number;
}

export interface ClientRecord {
    id: string;
    name: string;
    notes: string;
    createdAt: number;
}

export interface PeopleRecord {
    id: string;
    name: string;
    role?: string;
    company?: string;
    location?: string;
    email?: string;
    phone?: string;
    attributes?: string[]; // e.g., "decision-maker", "technical", "gatekeeper", "influencer"
    connections?: Array<{
        personId: string;
        relationship: string; // e.g., "reports to", "collaborates with", "mentor", "peer"
        strength?: 'weak' | 'moderate' | 'strong';
        notes?: string;
    }>;
    profile?: string; // Rich profile/context about the person
    notes?: string; // General notes
    tags?: string[]; // Custom tags for categorization
    createdAt: number;
    updatedAt?: number;
}

export interface ConceptRecord {
    id: string;
    name: string;
    description?: string;
    category?: string; // e.g., "AI Application", "Technology", "Business Model", "Idea"
    tags?: string[];
    notes?: string;
    relatedConcepts?: string[]; // IDs of related concepts
    createdAt: number;
    updatedAt?: number;
}

export interface XPEvent {
    id: string;
    reason: string;
    points: number;
    createdAt: number;
    metadata?: string;
}

export interface GoalRecord {
    id: string;
    title: string;
    description: string;
    goalType: 'small' | 'big'; // Small goals vs big goals
    scope: 'personal' | 'professional';
    priority: 'low' | 'medium' | 'high';
    metrics: string;
    createdAt: number;
    updatedAt?: number;
}

export interface VendorTask {
    id: string;
    goalId: string;
    title: string;
    description: string;
    rationale?: string; // Why Sylvia thinks this task helps the goal
    estimatedEffort: 'very-low' | 'low' | 'medium' | 'high'; // Effort required
    estimatedImpact: 'very-low' | 'low' | 'medium' | 'high' | 'very-high'; // Impact on goal
    status: 'pending' | 'in-progress' | 'completed' | 'skipped' | 'failed';
    generatedAt: number; // When Sylvia generated this task
    completedAt?: number;
    completionNotes?: string; // User's notes on what happened
    outcome?: 'exceeded' | 'met' | 'below' | 'missed'; // How did it go?
    outcomeDetails?: string; // Detailed outcome description
    feedback?: {
        taskQuality: number; // 1-100: Was this a good task?
        effortAccuracy: number; // 1-100: Was effort estimate accurate?
        impactAccuracy: number; // 1-100: Was impact estimate accurate?
        clarity: number; // 1-100: Was the task clear?
        helpfulness: number; // 1-100: How helpful was this task?
        notes?: string; // Additional feedback
    };
    learningData?: {
        whatWorked?: string[];
        whatDidntWork?: string[];
        suggestions?: string;
    };
    createdAt: number;
    updatedAt?: number;
}

// Delta Trading System Types

export type EGateStatus = 'E0' | 'E1' | 'E2' | 'E3' | 'E4';
export type PADStatus = 'potential' | 'actualized' | 'deployed';

export interface StrategyState {
    id: string;
    name: string;
    eGate: EGateStatus;
    padStatus: PADStatus;
    deltaH: number; // ΔH* evidence score
    complexity: number;
    lowScore: number; // LOW score = ΔH* - λ·Complexity
    nullHypotheses: string[];
    createdAt: number;
    updatedAt?: number;
}

export interface LockState {
    id: string;
    strategyId: string;
    lockType: 'phase-lock' | 'copl'; // Phase-lock or Cross-Ontological Phase-Lock
    detected: boolean;
    strength: number; // 0-1
    description: string;
    createdAt: number;
}

export interface HazardItem {
    id: string;
    symbol: string; // Ticker symbol
    hazard: number; // h(t) = κ·ε·g·(1-ζ/ζ*)·u·p
    kappa: number; // κ (regime factor)
    epsilon: number; // ε (edge strength)
    g: number; // g(e_φ) (phase-lock gain)
    zeta: number; // ζ (current barrier)
    zetaStar: number; // ζ* (critical threshold)
    u: number; // u (urgency)
    p: number; // p (precision)
    recommendation: 'buy' | 'sell' | 'hold';
    createdAt: number;
}

export interface DeltaState {
    id: string;
    strategies: StrategyState[];
    locks: LockState[];
    hazards: HazardItem[];
    auditStats: {
        totalStrategies: number;
        e0Strategies: number;
        e1Strategies: number;
        e2Strategies: number;
        e3Strategies: number;
        e4Strategies: number;
        potentialStrategies: number;
        actualizedStrategies: number;
        deployedStrategies: number;
        avgDeltaH: number;
        avgLowScore: number;
    };
    updatedAt: number;
}
