
export enum MessageSender {
    USER = 'user',
    AI = 'ai',
}

export enum AppView {
    CHAT = 'chat',
    SETTINGS = 'settings',
    BRAND = 'brand',
    PEOPLE = 'people',
    CONCEPTS = 'concepts',
    JOURNAL = 'journal',
    AGENDA = 'agenda',
    CALENDAR = 'calendar',
    POMODORO = 'pomodoro',
    GAMIFICATION = 'gamification',
    POLARIS = 'polaris',
    SEARCH = 'search',
    TWITTER = 'twitter',
}

export interface FileAttachment {
    name: string;
    type: string;
    size: string;
}

export interface Message {
    id: string;
    threadId: string;
    sender: MessageSender;
    text: string;
    file?: FileAttachment;
    createdAt: number;
}

export interface Thread {
    id: string;
    title: string;
    createdAt: number;
    updatedAt: number;
    artifactContent?: string;
}

export interface JITSnippet {
    id: string;
    threadId: string;
    tags: string[];
    text: string;
    relevance: number;
    createdAt: number;
}

export interface JournalEntry {
    id: string;
    title: string;
    content: string;
    createdAt: number;
    autoGenerated?: boolean;
    sourceThreadId?: string;
    tags?: string[];
    grade?: number; // 1-5
    gradeNotes?: string;
    scope?: 'personal' | 'professional';
    sentiment?: 'positive' | 'neutral' | 'negative';
    metadata?: Record<string, string>;
}

export interface AgendaItem {
    id: string;
    title: string;
    description?: string;
    status: 'todo' | 'in-progress' | 'done';
    dueAt?: number;
    createdAt: number;
    deliverableId?: string;
    estimatedTime?: number; // Minutes
    priority?: 'low' | 'medium' | 'high';
    dependencies?: string[]; // IDs of tasks that must be completed first
    tags?: string[];
    completedAt?: number;
    notes?: string;
}

export interface Deliverable {
    id: string;
    title: string;
    description: string;
    scope: 'personal' | 'professional';
    priority: 'low' | 'medium' | 'high';
    tags: string[];
    guardrails: string;
    successCriteria: string;
    createdAt: number;
}

export interface AgendaSession {
    id: string;
    mode: 'manual' | 'semi-auto' | 'auto';
    deliverableIds: string[];
    taskSequence?: string[]; // Ordered list of agenda item IDs for workflow
    startedAt: number;
    endedAt?: number;
    status: 'active' | 'paused' | 'completed';
    summary?: string;
    notes?: string;
    currentTaskIndex?: number; // For tracking progress through sequence
    autonomousAgentConfig?: {
        personality?: string; // How the agent should act
        decisionStyle?: string; // How it makes decisions
        communicationStyle?: string; // How it communicates
    };
    sessionGoals?: string[]; // Goals for this session
    xpAwarded?: number; // XP earned during session
    createdAt?: number;
    updatedAt?: number;
}

export interface PostMortem {
    id: string;
    sessionId: string;
    notes: string;
    grade?: number;
    createdAt: number;
}

export interface CalendarEvent {
    id: string;
    title: string;
    description?: string;
    startAt: number;
    endAt: number;
    location?: string;
    meetingLink?: string;
    eventType?: 'meeting' | 'call' | 'appointment' | 'event' | 'deadline' | 'reminder' | 'other';
    participants?: string[]; // Array of PeopleRecord IDs
    tags?: string[];
    color?: string; // Hex color for calendar display
    isRecurring?: boolean;
    recurrenceRule?: string; // e.g., "daily", "weekly", "monthly"
    reminderMinutes?: number; // Minutes before event to remind
    createdAt: number;
    updatedAt?: number;
}

export interface PomodoroSession {
    id: string;
    label: string;
    startedAt: number;
    durationMinutes: number;
}

export interface BrandRecord {
    id: string;
    name: string;
    description: string;
    createdAt: number;
}

export interface ClientRecord {
    id: string;
    name: string;
    notes: string;
    createdAt: number;
}

export interface PeopleRecord {
    id: string;
    name: string;
    role?: string;
    company?: string;
    location?: string;
    email?: string;
    phone?: string;
    attributes?: string[]; // e.g., "decision-maker", "technical", "gatekeeper", "influencer"
    connections?: Array<{
        personId: string;
        relationship: string; // e.g., "reports to", "collaborates with", "mentor", "peer"
        strength?: 'weak' | 'moderate' | 'strong';
        notes?: string;
    }>;
    profile?: string; // Rich profile/context about the person
    notes?: string; // General notes
    tags?: string[]; // Custom tags for categorization
    createdAt: number;
    updatedAt?: number;
}

export interface ConceptRecord {
    id: string;
    name: string;
    description?: string;
    category?: string; // e.g., "AI Application", "Technology", "Business Model", "Idea"
    tags?: string[];
    notes?: string;
    relatedConcepts?: string[]; // IDs of related concepts
    createdAt: number;
    updatedAt?: number;
}

export interface XPEvent {
    id: string;
    reason: string;
    points: number;
    createdAt: number;
    metadata?: string;
}

export interface GoalRecord {
    id: string;
    title: string;
    description: string;
    goalType: 'small' | 'big'; // Small goals vs big goals
    scope: 'personal' | 'professional';
    priority: 'low' | 'medium' | 'high';
    metrics: string;
    createdAt: number;
    updatedAt?: number;
}

export interface VendorTask {
    id: string;
    goalId: string;
    title: string;
    description: string;
    rationale?: string; // Why Sylvia thinks this task helps the goal
    estimatedEffort: 'very-low' | 'low' | 'medium' | 'high'; // Effort required
    estimatedImpact: 'very-low' | 'low' | 'medium' | 'high' | 'very-high'; // Impact on goal
    status: 'pending' | 'in-progress' | 'completed' | 'skipped' | 'failed';
    generatedAt: number; // When Sylvia generated this task
    completedAt?: number;
    completionNotes?: string; // User's notes on what happened
    outcome?: 'exceeded' | 'met' | 'below' | 'missed'; // How did it go?
    outcomeDetails?: string; // Detailed outcome description
    feedback?: {
        taskQuality: number; // 1-100: Was this a good task?
        effortAccuracy: number; // 1-100: Was effort estimate accurate?
        impactAccuracy: number; // 1-100: Was impact estimate accurate?
        clarity: number; // 1-100: Was the task clear?
        helpfulness: number; // 1-100: How helpful was this task?
        notes?: string; // Additional feedback
    };
    learningData?: {
        whatWorked?: string[];
        whatDidntWork?: string[];
        suggestions?: string;
    };
    createdAt: number;
    updatedAt?: number;
}

// ===== Twitter/X Integration Types =====

export interface TwitterAccount {
    id: string;
    username: string;
    displayName: string;
    isConnected: boolean;
    apiKey?: string;
    apiSecret?: string;
    accessToken?: string;
    accessTokenSecret?: string;
    bearerToken?: string;
    createdAt: number;
    updatedAt?: number;
}

export interface TwitterDraft {
    id: string;
    content: string;
    mediaUrls?: string[];
    threadTweets?: string[]; // For thread drafts
    tags?: string[];
    isThread: boolean;
    replyToTweetId?: string; // If this is a reply
    quoteTweetId?: string; // If this is a quote tweet
    createdAt: number;
    updatedAt?: number;
}

export interface TwitterScheduledPost {
    id: string;
    content: string;
    scheduledAt: number; // Unix timestamp when to post
    mediaUrls?: string[];
    threadTweets?: string[]; // For scheduled threads
    tags?: string[];
    status: 'pending' | 'posted' | 'failed' | 'cancelled';
    postedAt?: number;
    tweetId?: string; // ID from Twitter after posting
    errorMessage?: string;
    replyToTweetId?: string;
    quoteTweetId?: string;
    createdAt: number;
    updatedAt?: number;
}

export interface TwitterAnalytics {
    id: string;
    tweetId: string;
    impressions?: number;
    engagements?: number;
    likes?: number;
    retweets?: number;
    replies?: number;
    profileClicks?: number;
    urlClicks?: number;
    hashtagClicks?: number;
    detailExpands?: number;
    permalink?: string;
    fetchedAt: number;
    createdAt: number;
}

export interface TwitterList {
    id: string;
    listId: string; // Twitter list ID
    name: string;
    description?: string;
    memberCount?: number;
    subscriberCount?: number;
    isPrivate: boolean;
    createdAt: number;
    updatedAt?: number;
}

export interface TwitterDM {
    id: string;
    conversationId: string;
    senderId: string;
    recipientId: string;
    content: string;
    mediaUrls?: string[];
    sentAt: number;
    readAt?: number;
    isRead: boolean;
    createdAt: number;
}

export interface TwitterHashtagTracker {
    id: string;
    hashtag: string;
    isActive: boolean;
    trackingStartedAt: number;
    lastCheckedAt?: number;
    tweetCount?: number;
    notes?: string;
    createdAt: number;
    updatedAt?: number;
}

export interface TwitterMention {
    id: string;
    tweetId: string;
    authorUsername: string;
    authorDisplayName: string;
    content: string;
    createdAt: number;
    isRead: boolean;
    repliedTo?: boolean;
    permalink?: string;
}

export interface TwitterThread {
    id: string;
    title?: string;
    tweets: Array<{
        content: string;
        mediaUrls?: string[];
    }>;
    status: 'draft' | 'scheduled' | 'posted';
    scheduledAt?: number;
    postedAt?: number;
    tweetIds?: string[]; // IDs from Twitter after posting
    tags?: string[];
    createdAt: number;
    updatedAt?: number;
}

export interface TwitterMetrics {
    id: string;
    date: string; // YYYY-MM-DD format
    followers: number;
    following: number;
    totalTweets: number;
    totalImpressions?: number;
    totalEngagements?: number;
    profileVisits?: number;
    mentions?: number;
    createdAt: number;
}
