import { captureSnippet } from './jitMemory';
import { entityStorage } from './storage';
import { JournalEntry } from '../types';

interface LogOptions {
  scope?: 'personal' | 'professional';
  sentiment?: 'positive' | 'neutral' | 'negative';
  tags?: string[];
  sourceThreadId?: string;
  metadata?: Record<string, string>;
  autoGenerated?: boolean;
}

export const logContext = async (title: string, content: string, options: LogOptions = {}) => {
  await captureSnippet(options.sourceThreadId || 'global', content);
  const entry: JournalEntry = {
    id: `journal-${Date.now()}`,
    title,
    content,
    createdAt: Date.now(),
    autoGenerated: options.autoGenerated,
    scope: options.scope,
    sentiment: options.sentiment,
    sourceThreadId: options.sourceThreadId,
    tags: options.tags,
    metadata: options.metadata,
  };
  await entityStorage.saveJournalEntry(entry);
};
