import React, { useEffect, useState, useCallback, useMemo } from 'react';
import PageShell from './PageShell';
import { JournalEntry, JITSnippet } from '../../types';
import { entityStorage, getRecentSnippets, getSetting, saveSetting } from '../../services/storage';
import { registerWriteSurface } from '../../services/writeAnywhere';
import { renderMarkdown } from '../../services/markdown';
import { awardExperience } from '../../services/experience';
import { deriveScopeFromTags } from '../../services/contextTags';
import MarkdownBlock from '../MarkdownBlock';
import { subscribeToEntityUpdates } from '../../services/entityEvents';
import { extractEntitiesFromJournalEntry } from '../../services/postProcessor';
import { useAppContext } from '../../context/AppContext';
import {
  FileText,
  Search,
  Filter,
  Calendar,
  Tag,
  Star,
  TrendingUp,
  Sparkles,
  X,
  Edit2,
  Trash2,
  RefreshCw,
  Zap,
  CheckCircle2,
  AlertCircle,
  Clock,
  BookOpen,
  Award,
  BarChart3,
} from 'lucide-react';

const JournalPage: React.FC = () => {
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [suggestions, setSuggestions] = useState<JITSnippet[]>([]);
  const [consumedSuggestionIds, setConsumedSuggestionIds] = useState<string[]>([]);
  const [editingEntry, setEditingEntry] = useState<JournalEntry | null>(null);
  const [editContent, setEditContent] = useState('');
  const [editTitle, setEditTitle] = useState('');
  const [extractingEntryId, setExtractingEntryId] = useState<string | null>(null);
  const [extractionResults, setExtractionResults] = useState<Record<string, { extracted: string[]; errors: string[] }>>({});
  const [searchQuery, setSearchQuery] = useState('');
  const [filterTag, setFilterTag] = useState<string | null>(null);
  const [filterGrade, setFilterGrade] = useState<number | null>(null);
  const [showSuggestions, setShowSuggestions] = useState(true);

  const stats = useMemo(() => {
    const total = entries.length;
    const auto = entries.filter(e => e.autoGenerated).length;
    const graded = entries.filter(e => typeof e.grade === 'number');
    const avgGrade = graded.length ? (graded.reduce((sum, e) => sum + (e.grade || 0), 0) / graded.length).toFixed(1) : '—';
    const thisWeek = entries.filter(e => {
      const entryDate = new Date(e.createdAt);
      const weekAgo = new Date();
      weekAgo.setDate(weekAgo.getDate() - 7);
      return entryDate >= weekAgo;
    }).length;
    const thisMonth = entries.filter(e => {
      const entryDate = new Date(e.createdAt);
      const monthAgo = new Date();
      monthAgo.setMonth(monthAgo.getMonth() - 1);
      return entryDate >= monthAgo;
    }).length;
    return { total, auto, avgGrade, graded: graded.length, thisWeek, thisMonth };
  }, [entries]);

  const allTags = useMemo(() => {
    const tagSet = new Set<string>();
    entries.forEach(entry => {
      entry.tags?.forEach(tag => tagSet.add(tag));
    });
    return Array.from(tagSet).sort();
  }, [entries]);

  const load = useCallback(async () => {
    const data = await entityStorage.getJournalEntries();
    setEntries(data.sort((a, b) => b.createdAt - a.createdAt));
  }, []);

  useEffect(() => {
    load();
    (async () => {
      const stored = await getSetting<string[]>('journal_consumed_snippets', []);
      setConsumedSuggestionIds(stored);
    })();
    const unregisterSurface = registerWriteSurface({
      id: 'journal',
      label: 'Journal',
      onRequest: (prompt) => setContent((prev) => `${prompt}\n\n${prev}`.trim()),
    });
    return unregisterSurface;
  }, [load]);

  const refreshSuggestions = useCallback(async () => {
    const snippets = await getRecentSnippets(6);
    const filtered = snippets.filter(snippet => !consumedSuggestionIds.includes(snippet.id));
    setSuggestions(filtered);
  }, [consumedSuggestionIds]);

  useEffect(() => {
    refreshSuggestions();
  }, [refreshSuggestions, entries]);

  const createEntry = useCallback(async (entryTitle: string, entryContent: string, options?: Partial<JournalEntry>) => {
    if (!entryContent.trim()) return;
    await entityStorage.saveJournalEntry({
      id: `journal-${Date.now()}`,
      title: entryTitle || 'Untitled entry',
      content: entryContent,
      createdAt: Date.now(),
      ...options,
    });
    await load();
    await awardExperience('journal.entry');
    setTitle('');
    setContent('');
  }, [load]);

  const handleAdd = async () => {
    await createEntry(title, content);
  };

  const handleDeleteEntry = async (entryId: string) => {
    await entityStorage.deleteJournalEntry(entryId);
    load();
  };

  const startEdit = (entry: JournalEntry) => {
    setEditingEntry(entry);
    setEditTitle(entry.title);
    setEditContent(entry.content);
    setActiveEntity({ type: 'journal', id: entry.id, data: entry });
  };

  const saveEdit = async () => {
    if (!editingEntry) return;
    await entityStorage.saveJournalEntry({
      ...editingEntry,
      title: editTitle,
      content: editContent,
    });
    setEditingEntry(null);
    setEditTitle('');
    setEditContent('');
    setActiveEntity({ type: null, id: '' });
    load();
  };

  const cancelEdit = () => {
    setEditingEntry(null);
    setActiveEntity({ type: null, id: '' });
    setEditTitle('');
    setEditContent('');
  };

  const handleExtractEntities = async (entryId: string) => {
    setExtractingEntryId(entryId);
    
    try {
      const auditApiKey = await getSetting('auditApiKey', '');
      const primaryApiKey = await getSetting('apiKey', '');
      const apiKey = auditApiKey || primaryApiKey;
      
      if (!apiKey) {
        setExtractionResults(prev => ({
          ...prev,
          [entryId]: { extracted: [], errors: ['No API key configured. Please add an API key in Settings.'] },
        }));
        return;
      }
      
      const result = await extractEntitiesFromJournalEntry(entryId, apiKey);
      setExtractionResults(prev => ({
        ...prev,
        [entryId]: result,
      }));
      
      await load();
    } catch (error) {
      setExtractionResults(prev => ({
        ...prev,
        [entryId]: {
          extracted: [],
          errors: [error instanceof Error ? error.message : 'Failed to extract entities'],
        },
      }));
    } finally {
      setExtractingEntryId(null);
    }
  };

  useEffect(() => {
    const unsubscribe = subscribeToEntityUpdates('journal', load);
    return unsubscribe;
  }, [load]);

  const filteredEntries = useMemo(() => {
    let filtered = entries;

    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      filtered = filtered.filter(entry =>
        entry.title.toLowerCase().includes(query) ||
        entry.content.toLowerCase().includes(query) ||
        entry.tags?.some(tag => tag.toLowerCase().includes(query))
      );
    }

    if (filterTag) {
      filtered = filtered.filter(entry => entry.tags?.includes(filterTag));
    }

    if (filterGrade !== null) {
      filtered = filtered.filter(entry => entry.grade === filterGrade);
    }

    return filtered;
  }, [entries, searchQuery, filterTag, filterGrade]);

  const formatDate = (timestamp: number) => {
    const date = new Date(timestamp);
    const today = new Date();
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);

    if (date.toDateString() === today.toDateString()) {
      return 'Today';
    } else if (date.toDateString() === yesterday.toDateString()) {
      return 'Yesterday';
    } else {
      return date.toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: date.getFullYear() !== today.getFullYear() ? 'numeric' : undefined,
      });
    }
  };

  const getGradeColor = (grade?: number) => {
    if (!grade) return 'text-gray-400';
    if (grade >= 4) return 'text-green-600';
    if (grade >= 3) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getGradeBgColor = (grade?: number) => {
    if (!grade) return 'bg-gray-100';
    if (grade >= 4) return 'bg-green-100';
    if (grade >= 3) return 'bg-yellow-100';
    return 'bg-red-100';
  };

  return (
    <PageShell
      title="Journal"
      subtitle="Long-form reflections feed Sylvia's JIT memory. Rich context for understanding patterns and growth."
    >
      {/* Stats Overview */}
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-4 mb-6">
        <div className="rounded-2xl border border-white/70 bg-gradient-to-br from-blue-50 to-blue-100 p-4">
          <div className="flex items-center justify-between mb-2">
            <BookOpen className="w-6 h-6 text-blue-600" />
            <span className="text-2xl font-bold text-black">{stats.total}</span>
          </div>
          <p className="text-xs uppercase tracking-[0.2em] text-gray-600">Total Entries</p>
        </div>
        <div className="rounded-2xl border border-white/70 bg-gradient-to-br from-purple-50 to-purple-100 p-4">
          <div className="flex items-center justify-between mb-2">
            <Sparkles className="w-6 h-6 text-purple-600" />
            <span className="text-2xl font-bold text-black">{stats.auto}</span>
          </div>
          <p className="text-xs uppercase tracking-[0.2em] text-gray-600">Sylvia Drops</p>
        </div>
        <div className="rounded-2xl border border-white/70 bg-gradient-to-br from-green-50 to-green-100 p-4">
          <div className="flex items-center justify-between mb-2">
            <Award className="w-6 h-6 text-green-600" />
            <span className="text-2xl font-bold text-black">{stats.graded}</span>
          </div>
          <p className="text-xs uppercase tracking-[0.2em] text-gray-600">Graded</p>
        </div>
        <div className="rounded-2xl border border-white/70 bg-gradient-to-br from-yellow-50 to-yellow-100 p-4">
          <div className="flex items-center justify-between mb-2">
            <Star className="w-6 h-6 text-yellow-600" />
            <span className="text-2xl font-bold text-black">{stats.avgGrade}</span>
          </div>
          <p className="text-xs uppercase tracking-[0.2em] text-gray-600">Avg Grade</p>
        </div>
        <div className="rounded-2xl border border-white/70 bg-gradient-to-br from-orange-50 to-orange-100 p-4">
          <div className="flex items-center justify-between mb-2">
            <Clock className="w-6 h-6 text-orange-600" />
            <span className="text-2xl font-bold text-black">{stats.thisWeek}</span>
          </div>
          <p className="text-xs uppercase tracking-[0.2em] text-gray-600">This Week</p>
        </div>
        <div className="rounded-2xl border border-white/70 bg-gradient-to-br from-pink-50 to-pink-100 p-4">
          <div className="flex items-center justify-between mb-2">
            <BarChart3 className="w-6 h-6 text-pink-600" />
            <span className="text-2xl font-bold text-black">{stats.thisMonth}</span>
          </div>
          <p className="text-xs uppercase tracking-[0.2em] text-gray-600">This Month</p>
        </div>
      </div>

      {/* Sylvia Suggestions */}
      {showSuggestions && suggestions.length > 0 && (
        <div className="glass-panel border border-white/70 rounded-3xl p-6 mb-6 space-y-4 bg-gradient-to-br from-purple-50/50 to-pink-50/50">
          <div className="flex items-center justify-between">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <Sparkles className="w-5 h-5 text-purple-600" />
                <p className="text-xs uppercase tracking-[0.3em] text-purple-600 font-semibold">Sylvia Suggestions</p>
              </div>
              <h3 className="text-xl font-semibold">Promote to journal</h3>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={refreshSuggestions}
                className="px-3 py-1.5 rounded-full bg-white border border-white/70 text-sm hover:bg-gray-50 transition flex items-center gap-1"
              >
                <RefreshCw className="w-4 h-4" />
                Refresh
              </button>
              <button
                onClick={() => setShowSuggestions(false)}
                className="p-1.5 rounded-full bg-white border border-white/70 hover:bg-gray-50 transition"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {suggestions.map(snippet => (
              <div
                key={snippet.id}
                className="rounded-2xl border border-dashed border-purple-200 p-4 space-y-3 bg-white/80 hover:bg-white transition"
              >
                <div className="flex items-center justify-between">
                  <p className="text-xs uppercase tracking-[0.2em] text-secondary-light">Thread {snippet.threadId}</p>
                  <span className="px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 text-xs font-medium">
                    Suggestion
                  </span>
                </div>
                <div className="message-content text-sm" dangerouslySetInnerHTML={{ __html: renderMarkdown(snippet.text.substring(0, 200)) }} />
                {snippet.tags.length > 0 && (
                  <div className="flex flex-wrap gap-1.5">
                    {snippet.tags.map(tag => (
                      <span key={tag} className="px-2 py-0.5 rounded-full bg-purple-50 text-purple-700 text-xs border border-purple-100">
                        #{tag}
                      </span>
                    ))}
                  </div>
                )}
                <div className="flex gap-2">
                  <button
                    onClick={async () => {
                      await createEntry(snippet.tags[0] || 'Auto entry', snippet.text, {
                        autoGenerated: true,
                        sourceThreadId: snippet.threadId,
                        tags: snippet.tags,
                        scope: deriveScopeFromTags(snippet.tags),
                      });
                      const updated = [...consumedSuggestionIds, snippet.id];
                      setConsumedSuggestionIds(updated);
                      await saveSetting('journal_consumed_snippets', updated);
                      refreshSuggestions();
                    }}
                    className="flex-1 px-4 py-2 rounded-full bg-black text-white text-sm font-medium hover:shadow-lg transition"
                  >
                    Promote
                  </button>
                  <button
                    onClick={async () => {
                      const updated = [...consumedSuggestionIds, snippet.id];
                      setConsumedSuggestionIds(updated);
                      await saveSetting('journal_consumed_snippets', updated);
                      refreshSuggestions();
                    }}
                    className="px-4 py-2 rounded-full bg-white text-sm border border-white/70 hover:bg-gray-50 transition"
                  >
                    Dismiss
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Search and Filter */}
      <div className="mb-6 space-y-4">
        <div className="glass-panel rounded-2xl border border-white/70 p-4">
          <div className="flex items-center gap-3">
            <Search className="w-5 h-5 text-secondary-light" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search entries by title, content, or tags..."
              className="flex-1 bg-transparent outline-none text-lg placeholder:text-secondary-light"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="px-3 py-1 rounded-full bg-white/80 border border-white/70 text-sm hover:bg-white transition"
              >
                Clear
              </button>
            )}
          </div>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap gap-2 items-center">
          <span className="text-sm text-secondary-light flex items-center gap-1">
            <Filter className="w-4 h-4" />
            Filter:
          </span>
          <button
            onClick={() => setFilterTag(null)}
            className={`px-3 py-1 rounded-full text-xs font-medium transition ${
              filterTag === null
                ? 'bg-black text-white'
                : 'bg-white/80 border border-white/70 hover:bg-white'
            }`}
          >
            All Tags
          </button>
          {allTags.map(tag => (
            <button
              key={tag}
              onClick={() => setFilterTag(filterTag === tag ? null : tag)}
              className={`px-3 py-1 rounded-full text-xs font-medium transition flex items-center gap-1 ${
                filterTag === tag
                  ? 'bg-black text-white'
                  : 'bg-white/80 border border-white/70 hover:bg-white'
              }`}
            >
              <Tag className="w-3 h-3" />
              {tag}
            </button>
          ))}
          <div className="flex items-center gap-2 ml-2">
            <span className="text-xs text-secondary-light">Grade:</span>
            <button
              onClick={() => setFilterGrade(null)}
              className={`px-2 py-1 rounded-full text-xs transition ${
                filterGrade === null
                  ? 'bg-black text-white'
                  : 'bg-white/80 border border-white/70'
              }`}
            >
              All
            </button>
            {[5, 4, 3, 2, 1].map(grade => (
              <button
                key={grade}
                onClick={() => setFilterGrade(filterGrade === grade ? null : grade)}
                className={`px-2 py-1 rounded-full text-xs transition flex items-center gap-1 ${
                  filterGrade === grade
                    ? 'bg-black text-white'
                    : 'bg-white/80 border border-white/70'
                }`}
              >
                <Star className={`w-3 h-3 ${getGradeColor(grade)}`} />
                {grade}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Journal Entries */}
      {filteredEntries.length === 0 ? (
        <div className="glass-panel rounded-3xl border border-white/70 p-12 text-center">
          <div className="flex justify-center mb-4">
            <FileText className="w-16 h-16 text-secondary-light" />
          </div>
          <h3 className="text-xl font-semibold mb-2">
            {entries.length === 0 ? 'No journal entries yet' : 'No matches found'}
          </h3>
          <p className="text-secondary-light">
            {entries.length === 0
              ? "Start reflecting. Your thoughts become Sylvia's context."
              : 'Try adjusting your search or filters.'}
          </p>
        </div>
      ) : (
        <div className="space-y-6">
          {filteredEntries.map(entry => {
            const isEditing = editingEntry?.id === entry.id;
            const extractionResult = extractionResults[entry.id];
            const entryDate = new Date(entry.createdAt);

            return (
              <article
                key={entry.id}
                onClick={(e) => {
                  // Don't navigate if clicking buttons
                  if ((e.target as HTMLElement).closest('button')) return;
                  if (!isEditing) {
                    setActiveEntity({ type: 'journal', id: entry.id, data: entry });
                  }
                }}
                className={`rounded-3xl border p-6 transition-all cursor-pointer ${
                  isEditing
                    ? 'border-black bg-black text-white shadow-xl'
                    : 'border-white/70 bg-white/90 hover:shadow-lg hover:border-white'
                }`}
              >
                {isEditing ? (
                  <div className="space-y-4">
                    <div>
                      <label className="text-xs uppercase tracking-[0.2em] text-white/70 mb-2 block">
                        Title *
                      </label>
                      <input
                        value={editTitle}
                        onChange={(e) => setEditTitle(e.target.value)}
                        className="w-full rounded-2xl border border-white/30 bg-white/10 px-4 py-2 text-white placeholder:text-white/50 focus:outline-none focus:ring-2 focus:ring-white/50"
                        placeholder="Entry title"
                      />
                    </div>
                    <div>
                      <label className="text-xs uppercase tracking-[0.2em] text-white/70 mb-2 block">
                        Content *
                      </label>
                      <textarea
                        value={editContent}
                        onChange={(e) => setEditContent(e.target.value)}
                        rows={12}
                        className="w-full rounded-2xl border border-white/30 bg-white/10 px-4 py-2 text-white placeholder:text-white/50 focus:outline-none focus:ring-2 focus:ring-white/50 resize-none"
                        placeholder="Write your reflection..."
                      />
                    </div>
                    <div className="flex gap-2">
                      <button
                        onClick={saveEdit}
                        className="flex-1 px-4 py-2 rounded-2xl bg-white text-black font-semibold hover:bg-gray-100 transition"
                      >
                        Save
                      </button>
                      <button
                        onClick={cancelEdit}
                        className="px-4 py-2 rounded-2xl bg-white/20 text-white border border-white/30 hover:bg-white/30 transition"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                ) : (
                  <>
                    {/* Header */}
                    <header className="flex items-start justify-between mb-4">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-2">
                          <div className="flex items-center gap-2">
                            <Calendar className="w-4 h-4 text-secondary-light" />
                            <span className="text-xs uppercase tracking-[0.2em] text-secondary-light">
                              {formatDate(entry.createdAt)}
                            </span>
                            <span className="text-xs text-secondary-light">
                              {entryDate.toLocaleTimeString('en-US', {
                                hour: 'numeric',
                                minute: '2-digit',
                              })}
                            </span>
                          </div>
                          {entry.autoGenerated && (
                            <span className="px-2 py-0.5 rounded-full bg-purple-100 text-purple-700 text-xs font-medium flex items-center gap-1">
                              <Sparkles className="w-3 h-3" />
                              Sylvia
                            </span>
                          )}
                        </div>
                        <h3 className="text-2xl font-bold mb-2">{entry.title}</h3>
                      </div>
                      {entry.grade && (
                        <div
                          className={`px-3 py-1.5 rounded-full flex items-center gap-1 ${getGradeBgColor(entry.grade)}`}
                        >
                          <Star className={`w-4 h-4 ${getGradeColor(entry.grade)}`} />
                          <span className={`text-sm font-semibold ${getGradeColor(entry.grade)}`}>
                            {entry.grade}/5
                          </span>
                        </div>
                      )}
                    </header>

                    {/* Content */}
                    <div className="mb-4">
                      <MarkdownBlock content={entry.content} className="text-sm leading-relaxed" />
                    </div>

                    {/* Tags */}
                    {entry.tags && entry.tags.length > 0 && (
                      <div className="mb-4 flex flex-wrap gap-2">
                        {entry.tags.map(tag => (
                          <span
                            key={tag}
                            className="px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-medium border border-blue-100 flex items-center gap-1"
                          >
                            <Tag className="w-3 h-3" />
                            {tag}
                          </span>
                        ))}
                      </div>
                    )}

                    {/* Extraction Results */}
                    {extractionResult && extractingEntryId !== entry.id && (
                      <div
                        className={`mb-4 p-4 rounded-2xl border ${
                          extractionResult.extracted.length > 0
                            ? 'bg-green-50 border-green-200'
                            : extractionResult.errors.length > 0
                            ? 'bg-red-50 border-red-200'
                            : 'bg-gray-50 border-gray-200'
                        }`}
                      >
                        <div className="flex items-start justify-between mb-2">
                          <div className="flex items-center gap-2">
                            {extractionResult.extracted.length > 0 ? (
                              <CheckCircle2 className="w-4 h-4 text-green-600" />
                            ) : extractionResult.errors.length > 0 ? (
                              <AlertCircle className="w-4 h-4 text-red-600" />
                            ) : (
                              <Clock className="w-4 h-4 text-gray-600" />
                            )}
                            <span className="text-xs font-semibold uppercase tracking-[0.1em]">
                              Extraction Results
                            </span>
                          </div>
                          <button
                            onClick={() => {
                              setExtractionResults(prev => {
                                const next = { ...prev };
                                delete next[entry.id];
                                return next;
                              });
                            }}
                            className="text-gray-400 hover:text-gray-600 transition"
                          >
                            <X className="w-4 h-4" />
                          </button>
                        </div>
                        {extractionResult.extracted.length > 0 && (
                          <div className="mb-2">
                            <p className="text-xs font-semibold text-green-700 mb-1">
                              Extracted {extractionResult.extracted.length} entities:
                            </p>
                            <ul className="list-disc list-inside space-y-1 text-xs text-green-600">
                              {extractionResult.extracted.map((item, idx) => (
                                <li key={idx}>{item}</li>
                              ))}
                            </ul>
                          </div>
                        )}
                        {extractionResult.errors.length > 0 && (
                          <div>
                            <p className="text-xs font-semibold text-red-700 mb-1">Errors:</p>
                            <ul className="list-disc list-inside space-y-1 text-xs text-red-600">
                              {extractionResult.errors.map((error, idx) => (
                                <li key={idx}>{error}</li>
                              ))}
                            </ul>
                          </div>
                        )}
                        {extractionResult.extracted.length === 0 && extractionResult.errors.length === 0 && (
                          <p className="text-xs text-gray-600">No new entities found in this entry.</p>
                        )}
                      </div>
                    )}

                    {/* Actions */}
                    <div className="flex items-center gap-2 pt-4 border-t border-white/20">
                      <button
                        onClick={() => handleExtractEntities(entry.id)}
                        disabled={extractingEntryId === entry.id}
                        className="px-3 py-1.5 rounded-full bg-black text-white text-xs font-medium hover:shadow-lg transition flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed"
                        title="Extract entities from this entry (fail-safe)"
                      >
                        {extractingEntryId === entry.id ? (
                          <>
                            <RefreshCw className="w-3 h-3 animate-spin" />
                            Extracting...
                          </>
                        ) : (
                          <>
                            <Zap className="w-3 h-3" />
                            Extract Entities
                          </>
                        )}
                      </button>
                      <button
                        onClick={() => startEdit(entry)}
                        className="px-3 py-1.5 rounded-full bg-white/80 border border-white/70 text-xs font-medium hover:bg-white transition flex items-center gap-1"
                      >
                        <Edit2 className="w-3 h-3" />
                        Edit
                      </button>
                      <button
                        onClick={() => handleDeleteEntry(entry.id)}
                        className="px-3 py-1.5 rounded-full bg-white/80 border border-white/70 text-xs font-medium hover:bg-red-50 hover:border-red-200 hover:text-red-700 transition flex items-center gap-1"
                      >
                        <Trash2 className="w-3 h-3" />
                        Delete
                      </button>
                      <div className="flex items-center gap-2 ml-auto">
                        <select
                          value={entry.grade ?? ''}
                          onChange={async (e) => {
                            const grade = e.target.value ? Number(e.target.value) : undefined;
                            await entityStorage.saveJournalEntry({ ...entry, grade });
                            await awardExperience('journal.grade');
                            load();
                          }}
                          className="rounded-full border border-white/70 bg-white px-3 py-1 text-xs focus:outline-none focus:ring-2 focus:ring-black"
                        >
                          <option value="">Grade</option>
                          {[5, 4, 3, 2, 1].map(value => (
                            <option key={value} value={value}>
                              {value} ⭐
                            </option>
                          ))}
                        </select>
                        {entry.grade && (
                          <input
                            value={entry.gradeNotes ?? ''}
                            onChange={async (e) => {
                              await entityStorage.saveJournalEntry({ ...entry, gradeNotes: e.target.value });
                              load();
                            }}
                            placeholder="Grade notes..."
                            className="rounded-full border border-white/70 bg-white px-3 py-1 text-xs w-32 focus:outline-none focus:ring-2 focus:ring-black"
                          />
                        )}
                      </div>
                    </div>
                  </>
                )}
              </article>
            );
          })}
        </div>
      )}
    </PageShell>
  );
};

export default JournalPage;
